// Life expectancy data from WHO (World Health Organization)
// Source: WHO Global Health Observatory, 2021 Estimates
// This file is auto-generated by parse_who.cjs

export interface CountryLifeExpectancy {
    country: string;
    male: number;
    female: number;
}

export const parseDate = (birthdate: string): Date => {
    const [year, month, day] = birthdate.split("-").map(Number);
    return new Date(year, month - 1, day);
};

// World average fallback (WHO 2021)
export const mortalityStats = {
    male: 70.8,
    female: 75.9,
    source: "WHO Global Health Observatory (2021)"
};

export const whoData: Record<string, CountryLifeExpectancy> = {
    "Afghanistan": {
        "country": "Afghanistan",
        "male": 57.4,
        "female": 61
    },
    "Albania": {
        "country": "Albania",
        "male": 74.4,
        "female": 78.6
    },
    "Algeria": {
        "country": "Algeria",
        "male": 75.5,
        "female": 76.6
    },
    "Angola": {
        "country": "Angola",
        "male": 60,
        "female": 64.3
    },
    "Antigua and Barbuda": {
        "country": "Antigua and Barbuda",
        "male": 75.2,
        "female": 78.4
    },
    "Argentina": {
        "country": "Argentina",
        "male": 71.6,
        "female": 77.6
    },
    "Armenia": {
        "country": "Armenia",
        "male": 68.6,
        "female": 76.9
    },
    "Australia": {
        "country": "Australia",
        "male": 81.3,
        "female": 84.9
    },
    "Austria": {
        "country": "Austria",
        "male": 78.7,
        "female": 83.3
    },
    "Azerbaijan": {
        "country": "Azerbaijan",
        "male": 70.5,
        "female": 75.2
    },
    "Bahamas": {
        "country": "Bahamas",
        "male": 67.3,
        "female": 73.5
    },
    "Bahrain": {
        "country": "Bahrain",
        "male": 73.8,
        "female": 75.1
    },
    "Bangladesh": {
        "country": "Bangladesh",
        "male": 71.6,
        "female": 74.6
    },
    "Barbados": {
        "country": "Barbados",
        "male": 75.1,
        "female": 78.4
    },
    "Belarus": {
        "country": "Belarus",
        "male": 68.1,
        "female": 78.1
    },
    "Belgium": {
        "country": "Belgium",
        "male": 79.3,
        "female": 83.7
    },
    "Belize": {
        "country": "Belize",
        "male": 71.4,
        "female": 75.4
    },
    "Benin": {
        "country": "Benin",
        "male": 61.7,
        "female": 66.4
    },
    "Bhutan": {
        "country": "Bhutan",
        "male": 73.9,
        "female": 75.9
    },
    "Bolivia": {
        "country": "Bolivia",
        "male": 62.9,
        "female": 68.4
    },
    "Bosnia and Herzegovina": {
        "country": "Bosnia and Herzegovina",
        "male": 72.6,
        "female": 77.2
    },
    "Botswana": {
        "country": "Botswana",
        "male": 59.2,
        "female": 63.2
    },
    "Brazil": {
        "country": "Brazil",
        "male": 69,
        "female": 75.8
    },
    "Brunei": {
        "country": "Brunei",
        "male": 75.3,
        "female": 78.6
    },
    "Bulgaria": {
        "country": "Bulgaria",
        "male": 68,
        "female": 75
    },
    "Burkina Faso": {
        "country": "Burkina Faso",
        "male": 59.9,
        "female": 64.6
    },
    "Burundi": {
        "country": "Burundi",
        "male": 62,
        "female": 65.9
    },
    "Cabo Verde": {
        "country": "Cabo Verde",
        "male": 68.8,
        "female": 77.4
    },
    "Cambodia": {
        "country": "Cambodia",
        "male": 66.4,
        "female": 71.5
    },
    "Cameroon": {
        "country": "Cameroon",
        "male": 59.9,
        "female": 63.7
    },
    "Canada": {
        "country": "Canada",
        "male": 79.4,
        "female": 83.8
    },
    "Central African Republic": {
        "country": "Central African Republic",
        "male": 49.6,
        "female": 55.4
    },
    "Chad": {
        "country": "Chad",
        "male": 57.5,
        "female": 60.7
    },
    "Chile": {
        "country": "Chile",
        "male": 76.7,
        "female": 81.4
    },
    "China": {
        "country": "China",
        "male": 75,
        "female": 80.5
    },
    "Colombia": {
        "country": "Colombia",
        "male": 71.6,
        "female": 77.6
    },
    "Comoros": {
        "country": "Comoros",
        "male": 66.3,
        "female": 68.7
    },
    "Congo": {
        "country": "Congo",
        "male": 62.5,
        "female": 63.8
    },
    "Costa Rica": {
        "country": "Costa Rica",
        "male": 75.9,
        "female": 81.5
    },
    "Cote d'Ivoire": {
        "country": "Cote d'Ivoire",
        "male": 61.4,
        "female": 66
    },
    "Croatia": {
        "country": "Croatia",
        "male": 73.8,
        "female": 80
    },
    "Cuba": {
        "country": "Cuba",
        "male": 71.1,
        "female": 76.5
    },
    "Cyprus": {
        "country": "Cyprus",
        "male": 79.9,
        "female": 84
    },
    "Czechia": {
        "country": "Czechia",
        "male": 74,
        "female": 80.3
    },
    "DR Congo": {
        "country": "DR Congo",
        "male": 59.4,
        "female": 63.9
    },
    "Denmark": {
        "country": "Denmark",
        "male": 79.5,
        "female": 82.9
    },
    "Djibouti": {
        "country": "Djibouti",
        "male": 63,
        "female": 66.7
    },
    "Dominican Republic": {
        "country": "Dominican Republic",
        "male": 70.2,
        "female": 76.8
    },
    "Ecuador": {
        "country": "Ecuador",
        "male": 71,
        "female": 77.2
    },
    "Egypt": {
        "country": "Egypt",
        "male": 66.7,
        "female": 71.7
    },
    "El Salvador": {
        "country": "El Salvador",
        "male": 66.8,
        "female": 76.2
    },
    "Equatorial Guinea": {
        "country": "Equatorial Guinea",
        "male": 60.2,
        "female": 63.2
    },
    "Eritrea": {
        "country": "Eritrea",
        "male": 60.9,
        "female": 66.2
    },
    "Estonia": {
        "country": "Estonia",
        "male": 72.8,
        "female": 81.2
    },
    "Eswatini": {
        "country": "Eswatini",
        "male": 51.6,
        "female": 57.9
    },
    "Ethiopia": {
        "country": "Ethiopia",
        "male": 66,
        "female": 69.7
    },
    "Fiji": {
        "country": "Fiji",
        "male": 63.5,
        "female": 67.7
    },
    "Finland": {
        "country": "Finland",
        "male": 79,
        "female": 84.1
    },
    "France": {
        "country": "France",
        "male": 79.1,
        "female": 84.7
    },
    "Gabon": {
        "country": "Gabon",
        "male": 62.7,
        "female": 67.9
    },
    "Gambia": {
        "country": "Gambia",
        "male": 62.2,
        "female": 66.3
    },
    "Georgia": {
        "country": "Georgia",
        "male": 66.9,
        "female": 75.6
    },
    "Germany": {
        "country": "Germany",
        "male": 78.1,
        "female": 82.9
    },
    "Ghana": {
        "country": "Ghana",
        "male": 63.7,
        "female": 68.6
    },
    "Greece": {
        "country": "Greece",
        "male": 77.3,
        "female": 82
    },
    "Grenada": {
        "country": "Grenada",
        "male": 70.5,
        "female": 75.2
    },
    "Guatemala": {
        "country": "Guatemala",
        "male": 65.6,
        "female": 71.9
    },
    "Guinea": {
        "country": "Guinea",
        "male": 59.9,
        "female": 62.5
    },
    "Guinea-Bissau": {
        "country": "Guinea-Bissau",
        "male": 56.1,
        "female": 61.1
    },
    "Guyana": {
        "country": "Guyana",
        "male": 63,
        "female": 69.3
    },
    "Haiti": {
        "country": "Haiti",
        "male": 61.7,
        "female": 63.2
    },
    "Honduras": {
        "country": "Honduras",
        "male": 67.4,
        "female": 70.5
    },
    "Hungary": {
        "country": "Hungary",
        "male": 70.9,
        "female": 77.8
    },
    "Iceland": {
        "country": "Iceland",
        "male": 81.3,
        "female": 83.9
    },
    "India": {
        "country": "India",
        "male": 65.8,
        "female": 69
    },
    "Indonesia": {
        "country": "Indonesia",
        "male": 66.4,
        "female": 70.2
    },
    "Iran": {
        "country": "Iran",
        "male": 73.1,
        "female": 76.4
    },
    "Iraq": {
        "country": "Iraq",
        "male": 68.9,
        "female": 73.9
    },
    "Ireland": {
        "country": "Ireland",
        "male": 79.9,
        "female": 83.4
    },
    "Israel": {
        "country": "Israel",
        "male": 82.4,
        "female": 82.1
    },
    "Italy": {
        "country": "Italy",
        "male": 80,
        "female": 84.3
    },
    "Jamaica": {
        "country": "Jamaica",
        "male": 67.6,
        "female": 72.8
    },
    "Japan": {
        "country": "Japan",
        "male": 81.7,
        "female": 87.2
    },
    "Jordan": {
        "country": "Jordan",
        "male": 74.6,
        "female": 77
    },
    "Kazakhstan": {
        "country": "Kazakhstan",
        "male": 66.4,
        "female": 73.9
    },
    "Kenya": {
        "country": "Kenya",
        "male": 64.4,
        "female": 69.2
    },
    "Kiribati": {
        "country": "Kiribati",
        "male": 57.8,
        "female": 64
    },
    "Kuwait": {
        "country": "Kuwait",
        "male": 77.3,
        "female": 81.8
    },
    "Kyrgyzstan": {
        "country": "Kyrgyzstan",
        "male": 68.5,
        "female": 75.8
    },
    "Laos": {
        "country": "Laos",
        "male": 66.1,
        "female": 70.5
    },
    "Latvia": {
        "country": "Latvia",
        "male": 68.5,
        "female": 77.9
    },
    "Lebanon": {
        "country": "Lebanon",
        "male": 71.2,
        "female": 77.5
    },
    "Lesotho": {
        "country": "Lesotho",
        "male": 48.7,
        "female": 54.6
    },
    "Liberia": {
        "country": "Liberia",
        "male": 62.6,
        "female": 64.3
    },
    "Libya": {
        "country": "Libya",
        "male": 70.2,
        "female": 74.2
    },
    "Lithuania": {
        "country": "Lithuania",
        "male": 69.6,
        "female": 78.6
    },
    "Luxembourg": {
        "country": "Luxembourg",
        "male": 80.8,
        "female": 84.8
    },
    "Madagascar": {
        "country": "Madagascar",
        "male": 61.9,
        "female": 64
    },
    "Malawi": {
        "country": "Malawi",
        "male": 59.7,
        "female": 65.3
    },
    "Malaysia": {
        "country": "Malaysia",
        "male": 70.6,
        "female": 75.3
    },
    "Maldives": {
        "country": "Maldives",
        "male": 74.5,
        "female": 76.6
    },
    "Mali": {
        "country": "Mali",
        "male": 61.1,
        "female": 62.3
    },
    "Malta": {
        "country": "Malta",
        "male": 80,
        "female": 83.7
    },
    "Mauritania": {
        "country": "Mauritania",
        "male": 68.4,
        "female": 69.4
    },
    "Mauritius": {
        "country": "Mauritius",
        "male": 70.1,
        "female": 76.9
    },
    "Mexico": {
        "country": "Mexico",
        "male": 67.2,
        "female": 74.7
    },
    "Micronesia": {
        "country": "Micronesia",
        "male": 63,
        "female": 68.7
    },
    "Moldova": {
        "country": "Moldova",
        "male": 65.5,
        "female": 73.6
    },
    "Mongolia": {
        "country": "Mongolia",
        "male": 66.4,
        "female": 73.9
    },
    "Montenegro": {
        "country": "Montenegro",
        "male": 71.6,
        "female": 77.9
    },
    "Morocco": {
        "country": "Morocco",
        "male": 71.5,
        "female": 73.7
    },
    "Mozambique": {
        "country": "Mozambique",
        "male": 54.8,
        "female": 60.5
    },
    "Myanmar": {
        "country": "Myanmar",
        "male": 64.7,
        "female": 71.1
    },
    "Namibia": {
        "country": "Namibia",
        "male": 57.3,
        "female": 63.4
    },
    "Nepal": {
        "country": "Nepal",
        "male": 68.3,
        "female": 71.8
    },
    "Netherlands": {
        "country": "Netherlands",
        "male": 79.6,
        "female": 82.6
    },
    "New Zealand": {
        "country": "New Zealand",
        "male": 80.4,
        "female": 84
    },
    "Nicaragua": {
        "country": "Nicaragua",
        "male": 72.3,
        "female": 77.7
    },
    "Niger": {
        "country": "Niger",
        "male": 59,
        "female": 60.9
    },
    "Nigeria": {
        "country": "Nigeria",
        "male": 62.1,
        "female": 64.8
    },
    "North Korea": {
        "country": "North Korea",
        "male": 69.8,
        "female": 75.6
    },
    "North Macedonia": {
        "country": "North Macedonia",
        "male": 70.9,
        "female": 75.2
    },
    "Norway": {
        "country": "Norway",
        "male": 81.5,
        "female": 84.3
    },
    "Oman": {
        "country": "Oman",
        "male": 70.9,
        "female": 74.9
    },
    "Pakistan": {
        "country": "Pakistan",
        "male": 65.1,
        "female": 66.9
    },
    "Palestine": {
        "country": "Palestine",
        "male": 71.1,
        "female": 75.9
    },
    "Panama": {
        "country": "Panama",
        "male": 74.4,
        "female": 80.3
    },
    "Papua New Guinea": {
        "country": "Papua New Guinea",
        "male": 64.2,
        "female": 66.9
    },
    "Paraguay": {
        "country": "Paraguay",
        "male": 67.6,
        "female": 73.2
    },
    "Peru": {
        "country": "Peru",
        "male": 68.8,
        "female": 74.8
    },
    "Philippines": {
        "country": "Philippines",
        "male": 63.4,
        "female": 69.9
    },
    "Poland": {
        "country": "Poland",
        "male": 71.6,
        "female": 79.4
    },
    "Portugal": {
        "country": "Portugal",
        "male": 78.3,
        "female": 83.9
    },
    "Puerto Rico": {
        "country": "Puerto Rico",
        "male": 76.2,
        "female": 83.5
    },
    "Qatar": {
        "country": "Qatar",
        "male": 76,
        "female": 78
    },
    "Romania": {
        "country": "Romania",
        "male": 69.2,
        "female": 76.5
    },
    "Russia": {
        "country": "Russia",
        "male": 65.6,
        "female": 74.3
    },
    "Rwanda": {
        "country": "Rwanda",
        "male": 65.4,
        "female": 69.4
    },
    "Saint Lucia": {
        "country": "Saint Lucia",
        "male": 68,
        "female": 74.5
    },
    "Saint Vincent and the Grenadines": {
        "country": "Saint Vincent and the Grenadines",
        "male": 70,
        "female": 75.5
    },
    "Samoa": {
        "country": "Samoa",
        "male": 69.1,
        "female": 71.6
    },
    "Sao Tome and Principe": {
        "country": "Sao Tome and Principe",
        "male": 69.6,
        "female": 72.8
    },
    "Saudi Arabia": {
        "country": "Saudi Arabia",
        "male": 75.7,
        "female": 77.4
    },
    "Senegal": {
        "country": "Senegal",
        "male": 65.9,
        "female": 69.5
    },
    "Serbia": {
        "country": "Serbia",
        "male": 70,
        "female": 75.6
    },
    "Seychelles": {
        "country": "Seychelles",
        "male": 72.6,
        "female": 75.6
    },
    "Sierra Leone": {
        "country": "Sierra Leone",
        "male": 60.2,
        "female": 61.9
    },
    "Singapore": {
        "country": "Singapore",
        "male": 81.6,
        "female": 86.3
    },
    "Slovakia": {
        "country": "Slovakia",
        "male": 71.1,
        "female": 78
    },
    "Slovenia": {
        "country": "Slovenia",
        "male": 77.5,
        "female": 83.4
    },
    "Solomon Islands": {
        "country": "Solomon Islands",
        "male": 62.6,
        "female": 67.3
    },
    "Somalia": {
        "country": "Somalia",
        "male": 51.7,
        "female": 56.3
    },
    "South Africa": {
        "country": "South Africa",
        "male": 58.9,
        "female": 64
    },
    "South Korea": {
        "country": "South Korea",
        "male": 80.7,
        "female": 86.7
    },
    "South Sudan": {
        "country": "South Sudan",
        "male": 56.5,
        "female": 60.6
    },
    "Spain": {
        "country": "Spain",
        "male": 80,
        "female": 85.3
    },
    "Sri Lanka": {
        "country": "Sri Lanka",
        "male": 74.2,
        "female": 80.1
    },
    "Sudan": {
        "country": "Sudan",
        "male": 66.2,
        "female": 68.9
    },
    "Suriname": {
        "country": "Suriname",
        "male": 67,
        "female": 72.7
    },
    "Sweden": {
        "country": "Sweden",
        "male": 81,
        "female": 84.3
    },
    "Switzerland": {
        "country": "Switzerland",
        "male": 81.5,
        "female": 85.1
    },
    "Syria": {
        "country": "Syria",
        "male": 70.6,
        "female": 74.4
    },
    "Tajikistan": {
        "country": "Tajikistan",
        "male": 70.2,
        "female": 73.5
    },
    "Tanzania": {
        "country": "Tanzania",
        "male": 65.2,
        "female": 68.4
    },
    "Thailand": {
        "country": "Thailand",
        "male": 71.8,
        "female": 79
    },
    "Timor-Leste": {
        "country": "Timor-Leste",
        "male": 66.5,
        "female": 69.6
    },
    "Togo": {
        "country": "Togo",
        "male": 61.5,
        "female": 66.4
    },
    "Tonga": {
        "country": "Tonga",
        "male": 70.2,
        "female": 75.3
    },
    "Trinidad and Tobago": {
        "country": "Trinidad and Tobago",
        "male": 68.4,
        "female": 75.2
    },
    "Tunisia": {
        "country": "Tunisia",
        "male": 71.5,
        "female": 76.8
    },
    "Turkey": {
        "country": "Turkey",
        "male": 72.5,
        "female": 78.1
    },
    "Turkmenistan": {
        "country": "Turkmenistan",
        "male": 65.7,
        "female": 72.5
    },
    "Uganda": {
        "country": "Uganda",
        "male": 62.9,
        "female": 69
    },
    "Ukraine": {
        "country": "Ukraine",
        "male": 66.3,
        "female": 75.3
    },
    "United Arab Emirates": {
        "country": "United Arab Emirates",
        "male": 77.2,
        "female": 80
    },
    "United Kingdom": {
        "country": "United Kingdom",
        "male": 78.3,
        "female": 81.9
    },
    "United States": {
        "country": "United States",
        "male": 73.7,
        "female": 79.1
    },
    "Uruguay": {
        "country": "Uruguay",
        "male": 71.2,
        "female": 78.7
    },
    "Uzbekistan": {
        "country": "Uzbekistan",
        "male": 70.2,
        "female": 74.1
    },
    "Vanuatu": {
        "country": "Vanuatu",
        "male": 63.4,
        "female": 69.8
    },
    "Venezuela": {
        "country": "Venezuela",
        "male": 66.9,
        "female": 75.9
    },
    "Vietnam": {
        "country": "Vietnam",
        "male": 69.7,
        "female": 78
    },
    "Yemen": {
        "country": "Yemen",
        "male": 63.1,
        "female": 68.6
    },
    "Zambia": {
        "country": "Zambia",
        "male": 58.7,
        "female": 63.1
    },
    "Zimbabwe": {
        "country": "Zimbabwe",
        "male": 56.2,
        "female": 60.5
    }
};

export function getCountryLifeExpectancy(countryName: string, gender: "Male" | "Female"): number | null {
    const data = whoData[countryName];
    if (!data) return null;
    return gender === "Male" ? data.male : data.female;
}

export function getAllCountryNames(): string[] {
    return Object.keys(whoData).sort();
}
